[[pages]]
path = "activity_tracker.py"
name = "Activity Tracker"
icon = ":clock:"

# [[pages]]
# path = "pages/Page_2.py"
# name = "Page 2"
# icon = "🚧"

# [[pages]]
# path = "pages/Page_3.py"
# name = "Page 3"
# icon = ":books:"