[[pages]]
path = "Activity_Tracker.py"
name = "Activity Tracker"
icon = ":alarmclock:"

[[pages]]
path = "pages/Page_2.py"
name = "Page 2 Under Contsruction"
icon = "🚧"

# [[pages]]
# path = "pages/Page_3.py"
# name = "Page 3"
# icon = ":books:"